DROP DATABASE IF EXISTS agrolink;
CREATE DATABASE agrolink;
USE agrolink;

CREATE TABLE User (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(150) NOT NULL UNIQUE,
    phone CHAR(11) NOT NULL UNIQUE,
    zip_code CHAR(8) NOT NULL,
    city VARCHAR(200) NOT NULL,
    state VARCHAR(200) NOT NULL,
	name VARCHAR(250) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Retailer (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    store_name VARCHAR(250) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES User(id)
);

CREATE TABLE Producer (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    farm_name VARCHAR(250) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES User(id)
);

CREATE TABLE Favorite (
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    producer_id INT NOT NULL,
	FOREIGN KEY (producer_id) REFERENCES Producer (id),
    retailer_id INT NOT NULL,
	FOREIGN KEY (retailer_id) REFERENCES Retailer (id),
    
    PRIMARY KEY (producer_id, retailer_id)
);

CREATE TABLE Product (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    unit_measure VARCHAR(10) NOT NULL,
    description VARCHAR(200) NOT NULL,
    available_inventory DOUBLE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   
    producer_id INT NOT NULL,
    FOREIGN KEY (producer_id) REFERENCES Producer(id)
);

CREATE TABLE Contact (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(150) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Product_Price_Log (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    product_id INT NOT NULL,
    old_price DECIMAL(10, 2) NOT NULL,
    new_price DECIMAL(10, 2) NOT NULL,
    changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (product_id) REFERENCES Product(id) ON DELETE CASCADE
);